---

- name: INCLUDE | Debian family
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags: install

- name: INCLUDE | RedHat family
  include_tasks: centos.yml
  when: ansible_os_family == "RedHat"
  tags: install

- name: IMPORT | Manage VG
  import_tasks: manage_lvm_vg.yml
  when:
    - lvm_action is defined
    - lvm_action == "add_vg" or lvm_action == "del_vg"

- name: IMPORT | Apply
  import_tasks: manage_lvm.yml
  when:
    - lvm_apply
    - lvm_action|default("") == ""
